version: '3'
services:

  helloworld:
    ports:
      - 8080:8080
    container_name: helloworld
    image: "ppcololo/helloworld:latest"

  prometheus:
    container_name: prometheus
    ports:
      - 9090:9090
    image: "prom/prometheus"
    depends_on:
      - helloworld
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: "grafana/grafana"
    depends_on:
      - prometheus
    volumes:
      - ./configs/grafana_dashboard.json:/etc/grafana/provisioning/dashboards/grafana_dashboard.json
      - ./configs/grafana_dashboard.yml:/etc/grafana/provisioning/dashboards/grafana_dashboard.yml
      - ./configs/grafana_datasource.yml:/etc/grafana/provisioning/datasources/grafana_datasource.yml
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

