apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Values.chartName }}
    version: "{{ .Values.image.tag }}"
    chart: {{ .Values.chartName }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    release: {{ .Release.Name }}
  type: ClusterIP